laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');
    Route::get('servicos', 'ServicosController@index')->name('servicos');
    Route::post('servicos', 'ServicosController@post')->name('servicos.post');
    Route::get('produtos', 'ProdutosController@index')->name('produtos');
    Route::post('produtos', 'ProdutosController@post')->name('produtos.post');
    Route::get('solicite-um-orcamento', 'ServicosController@index')->name('orcamento');
    Route::get('fale-conosco', 'ContatoController@index')->name('contato');
    Route::post('fale-conosco', 'ContatoController@post')->name('contato.post');


    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('o-que-oferecemos', 'OQueOferecemosController');
		Route::get('o-que-oferecemos/{o_que_oferecemos}/imagens/clear', [
			'as'   => 'painel.o-que-oferecemos.imagens.clear',
			'uses' => 'OQueOferecemosImagensController@clear'
		]);
		Route::resource('o-que-oferecemos.imagens', 'OQueOferecemosImagensController', ['parameters' => ['imagens' => 'imagens_o-que-oferecemos']]);
		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
		Route::resource('utilizacoes', 'UtilizacoesController');
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
		Route::resource('servicos', 'ServicosController', ['only' => ['index', 'update']]);
		Route::resource('financiamentos', 'FinanciamentosController');
		Route::resource('produtostexto', 'ProdutostextoController', ['only' => ['index', 'update']]);
		Route::resource('produtos', 'ProdutosController');

        Route::get('orcamentos-produtos/{orcamentos_produtos}/toggle', ['as' => 'painel.orcamentos-produtos.toggle', 'uses' => 'OrcamentosProdutosController@toggle']);
        Route::resource('orcamentos-produtos', 'OrcamentosProdutosController');
        Route::get('orcamentos-servicos/{orcamentos_servicos}/toggle', ['as' => 'painel.orcamentos-servicos.toggle', 'uses' => 'OrcamentosServicosController@toggle']);
        Route::resource('orcamentos-servicos', 'OrcamentosServicosController');

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }

    public function toggle(ContatoRecebido $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/EmpresaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EmpresaRequest;
use App\Http\Controllers\Controller;

use App\Models\Empresa;

class EmpresaController extends Controller
{
    public function index()
    {
        $registro = Empresa::first();

        return view('painel.empresa.edit', compact('registro'));
    }

    public function update(EmpresaRequest $request, Empresa $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_1'])) $input['imagem_1'] = Empresa::upload_imagem_1();
            if (isset($input['imagem_2'])) $input['imagem_2'] = Empresa::upload_imagem_2();

            $registro->update($input);

            return redirect()->route('painel.empresa.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/FinanciamentosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\FinanciamentosRequest;
use App\Http\Controllers\Controller;

use App\Models\Financiamento;

class FinanciamentosController extends Controller
{
    public function index()
    {
        $registros = Financiamento::ordenados()->get();

        return view('painel.financiamentos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.financiamentos.create');
    }

    public function store(FinanciamentosRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Financiamento::upload_imagem();

            Financiamento::create($input);

            return redirect()->route('painel.financiamentos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Financiamento $registro)
    {
        return view('painel.financiamentos.edit', compact('registro'));
    }

    public function update(FinanciamentosRequest $request, Financiamento $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Financiamento::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.financiamentos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Financiamento $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.financiamentos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/GeneratorController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Artisan;

class GeneratorController extends Controller
{
    public function index()
    {
        return view('painel.generator.index');
    }

    public function submit(Request $request)
    {
        $this->validate($request, [
            'type'         => 'required',
            'resourceName' => 'required',
            'unitName'     => 'required_if:type,default'
        ]);

        $type = $request->get('type');

        $parameters = [
            'resourceName' => $request->get('resourceName'),
            'fields'       => $request->get('fields'),
        ];

        if(!empty($request->get('campos_nome')[0])) {
            $fields = '';
            foreach ($request->get('campos_nome') as $key => $campo_nome) {
                $field = [
                    $campo_nome,
                    $request->get('campos_tipo')[$key],
                    $request->get('campos_validation')[$key]
                ];

                $field = implode(':', $field);

                if (array_key_exists($key+1, $request->get('campos_nome'))) {
                    $fields .= $field.',';
                } else {
                    $fields .= $field;
                }
            }

            if (!empty($request->get('fields'))) {
                $parameters['fields'] = $request->get('fields').','.$fields;
            } else {
                $parameters['fields'] = $fields;
            }
        }

        if ($type == 'default') {
            $parameters['unitName'] = $request->get('unitName');
            $parameters['--slug']   = $request->get('slug');

            if ($request->get('paginate')) {
                $parameters['--paginate'] = $request->get('paginate');
            }
            if ($request->get('sortable')) {
                $parameters['--sortable'] = true;
            }
            if ($request->get('gallery')) {
                $parameters['--gallery'] = true;
            }
            if ($request->get('categories')) {
                $parameters['--categories'] = true;
            }
            if ($request->get('tags')) {
                $parameters['--tags'] = true;
            }
        }

        if ($request->get('force')) {
            $parameters['--force'] = true;
        }

        try {

            Artisan::call('resource:'.$type, $parameters);
            $output = Artisan::output();

            return back()->with(compact('output'))->withInput();

        } catch (\Exception $e) {

            return back()->withErrors([$e->getMessage()])->withInput();

        }

    }
}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\HomeRequest;
use App\Http\Controllers\Controller;

use App\Models\Home;

class HomeController extends Controller
{
    public function index()
    {
        $registro = Home::first();

        return view('painel.home.edit', compact('registro'));
    }

    public function update(HomeRequest $request, Home $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['chamada_1_icone'])) $input['chamada_1_icone'] = Home::upload_chamada_1_icone();
            if (isset($input['chamada_2_icone'])) $input['chamada_2_icone'] = Home::upload_chamada_2_icone();
            if (isset($input['chamada_3_icone'])) $input['chamada_3_icone'] = Home::upload_chamada_3_icone();
            if (isset($input['imagem_lateral'])) $input['imagem_lateral'] = Home::upload_imagem_lateral();

            $registro->update($input);

            return redirect()->route('painel.home.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/OQueOferecemosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\OQueOferecemosRequest;
use App\Http\Controllers\Controller;

use App\Models\Quadro;

class OQueOferecemosController extends Controller
{
    public function index()
    {
        $registros = Quadro::ordenados()->get();

        return view('painel.o-que-oferecemos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.o-que-oferecemos.create');
    }

    public function store(OQueOferecemosRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Quadro::upload_imagem();

            Quadro::create($input);

            return redirect()->route('painel.o-que-oferecemos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Quadro $registro)
    {
        return view('painel.o-que-oferecemos.edit', compact('registro'));
    }

    public function update(OQueOferecemosRequest $request, Quadro $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Quadro::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.o-que-oferecemos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Quadro $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.o-que-oferecemos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/resources/views/painel/o-que-oferecemos/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Empresa / O que oferecemos /</small> Adicionar Quadro</h2>
    </legend>

    {!! Form::open(['route' => 'painel.o-que-oferecemos.store', 'files' => true]) !!}

        @include('painel.o-que-oferecemos.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/o-que-oferecemos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Empresa / O que oferecemos /</small> Editar Quadro</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.o-que-oferecemos.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.o-que-oferecemos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/o-que-oferecemos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto', 'Texto') !!}
    {!! Form::textarea('texto', null, ['class' => 'form-control', 'style' => 'resize:none']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem (opcional, só é exibida quando não houverem marcas cadastradas na galeria de imagens)') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/o-que-oferecemos/'.$registro->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
@endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.o-que-oferecemos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/o-que-oferecemos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.empresa.index') }}" class="btn btn-default btn-sm">
        &larr; Voltar para Empresa
    </a>

    <legend>
        <h2>
            <small>Empresa /</small> O que oferecemos
            <a href="{{ route('painel.o-que-oferecemos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Quadro</a>
        </h2>
    </legend>


    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="o_que_oferecemos">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th>Imagens</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $registro->titulo }}</td>
                <td><a href="{{ route('painel.o-que-oferecemos.imagens.index', $registro->id) }}" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-picture" style="margin-right:10px;"></span>Gerenciar
                </a></td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.o-que-oferecemos.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.o-que-oferecemos.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection